### PR TITLE
Replace custom error reporter with built-in Elixir error notification

### PR DESCRIPTION
**Pull request by jfoliveira**
- Using built-in Elixir error notification
- Remove custom Laravel Elixir Reporter
- Notifying succesful TypeScript compilation

### CODE REVIEW

**Comment by jfoliveira** [comment]
Thanks for merging this! Could you please make a new release available including this change? Thanks!

**Comment by jfoliveira** [comment]
Additionally, I think during your merge conflict resolution this line should remain as it has been added after my pull request:

``` javascript
var tsResult = gulp.src(assetPath + search)
```

Without it, the [Ability to compile just one .ts file](https://github.com/okaufmann/laravel-elixir-typescript/commit/f2e6726b77f6e08e67a0c2d5660c4c3cbcbdcf65) will be broken.

**Comment by okaufmann** [comment]
I'll just merged it this morning. When I have tested the changes, I'll tag a new version.

**Comment by jfoliveira** [comment]
Cool! Thanks for replying!

**Pull request merged**
